# Generated by Django 5.0.1 on 2026-02-05 23:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuantumPatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('scheme', models.CharField(choices=[('qpam', 'QPAM - Quantum Probability Amplitude Modulation'), ('sqpam', 'SQPAM - Single-Qubit PAM'), ('msqpam', 'MSQPAM - Multi-channel Single-Qubit PAM'), ('qsm', 'QSM - Quantum State Modulation'), ('mqsm', 'MQSM - Multi-channel Quantum State Modulation')], default='qpam', max_length=10)),
                ('shots', models.IntegerField(default=4000, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(8000)])),
                ('buffer_size', models.IntegerField(default=256)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessedSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_hash', models.CharField(db_index=True, max_length=64)),
                ('output_audio', models.BinaryField()),
                ('sample_rate', models.IntegerField(default=22050)),
                ('duration', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_samples', to='quantumsynth.quantumpatch')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patch', 'input_hash'], name='quantumsynt_patch_i_6b9995_idx')],
            },
        ),
    ]
